require('@4tw/cypress-drag-drop')

describe('tests', () => {
    beforeEach(function () {
        cy.visit('/')
    })
    it('TC01-Verify user can enter new data into the table', {defaultCommandTimeout: 5000}, () => {
        cy.get('.category-cards > :nth-child(1)').click()
        cy.get(':nth-child(1) > .element-list > .menu-list > #item-3')
            .should('be.visible')
            .click()
        cy.get('#addNewRecordButton')
            .should('be.visible')
            .click()
        assert.exists('#firstName', 'el is not exist')
        cy.get('#firstName').click().type('Alden')
        cy.get('#lastName')
            .should('be.visible')
            .click()
            .type('Cantrell')
        cy.get('#userEmail').click().type('files@files.com')
        cy.get('#age').click().type('30')
        cy.get('#salary').click().type('12345')
        cy.get('#department').click().type('QA')
        cy.get('#submit').click()
        cy.get('.ReactTable')
            .should('contain', 'files@files.com')
            .and('contain', 'Alden')
            .and('contain', 'Cantrell' )
            .and('contain', '30')
            .and('contain', '12345')
            .and('contain', 'QA')
    })
    it('TC01-Verify user can edit the row in a table', {defaultCommandTimeout: 5000}, () => {
        cy.get('.category-cards > :nth-child(1)').click()
        cy.get(':nth-child(1) > .element-list > .menu-list > #item-3').should('be.visible').click()
        cy.get('#addNewRecordButton')
            .should('be.visible')
            .click()
        assert.exists('#firstName', 'el is not exist')
        cy.get('#firstName')
            .click()
            .type('Alden')
        cy.get('#lastName')
            .should('be.visible')
            .click()
            .type('Cantrell')
        cy.get('#userEmail')
            .click()
            .type('files@files.com')
        cy.get('#age')
            .click()
            .type('30')
        cy.get('#salary')
            .click()
            .type('12345')
        cy.get('#department')
            .click()
            .type('QA')
        cy.get('#submit').click()
        cy.get('.ReactTable')
            .should('contain', 'files@files.com')
            .and('contain', 'Alden')
            .and('contain', 'Cantrell' )
            .and('contain', '30')
            .and('contain', '12345')
            .and('contain', 'QA')
        cy.get('#edit-record-2 > :nth-child(1)').click()
        cy.get('#firstName').clear().type('Gerimedica')
        cy.get('#lastName').clear().type('BV')
        cy.get('#submit').click()
        cy.get('.ReactTable')
            .should('contain', 'Gerimedica')
            .and('contain', 'BV')
    })
    it('TC02-Verify broken image', () => {
        cy.get('.category-cards > :nth-child(1)').click()
        cy.get(':nth-child(1) > .element-list > .menu-list > #item-3')
            .should('be.visible')
            .click()
        cy.get('.RightSide-Ad')
            .should('be.visible')
            .and('have.prop', 'naturalWidth')
    })
    it('TC03-Verify user can submit the form', () => {
        cy.get(':nth-child(2) > :nth-child(1) > .card-body > h5').click()
        cy.get(':nth-child(2) > .element-list > .menu-list > #item-0')
            .should('be.visible')
            .click()
        cy.get('#firstName').click().type('Gerimedica')
        cy.get('#lastName').click().type('BV')
        cy.get('#userEmail').click().type('files@files.com')
        cy.get('#genterWrapper > .col-md-9 > :nth-child(1)').click()
        cy.get('#userNumber').click().type('0123456789')
        cy.get('#dateOfBirthInput').type("{selectall}15 Jan 1990").type('{enter}')
        cy.get('.subjects-auto-complete__value-container').type('Cypress Assignment')
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(2)').click()
        cy.get('#uploadPicture').selectFile('cypress/files/dog.jpg')
        cy.get('#currentAddress').type('Netherlands')
        cy.get('#state').click().type('{downArrow}{enter}')
        cy.get('#city').click().type('{downArrow}{enter}')
        cy.get('#submit').click({force: true})
        cy.compareSnapshot('submit-form', .25)
    })
    it('TC04 - Verify the progress bar', () => {
        cy.get('.category-cards > :nth-child(4)').click()
        cy.scrollTo("bottom")
        cy.get(':nth-child(4) > .element-list > .menu-list > #item-4').click()
        cy.get('#startStopButton').click()
        cy.scrollTo("top")
        cy.get('.progress-bar')
            .should('have.css', 'background-color', 'rgb(40, 167, 69)')
    })
    it('TC05 - Verify the tooltip', () => {
        cy.get('.category-cards > :nth-child(4)').click()
        cy.scrollTo("bottom")
        cy.get(':nth-child(4) > .element-list > .menu-list > #item-6').click()
        cy.scrollTo("top")
        cy.get('#toolTipButton').trigger('mouseover')
        cy.get('.tooltip-inner').should('be.visible')
    })
    it('TC06 - Verify user can drag and drop', () => {
        cy.get('.category-cards > :nth-child(5) > :nth-child(1)').click()
        cy.scrollTo("bottom")
        cy.get(':nth-child(5) > .element-list > .menu-list > #item-3').click()
        cy.get('#draggable').drag('#droppable', {force: true})
    });
})